import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Filter, Search, X } from "lucide-react";
import { useLivePortfolio, type LiveAuditCategory, type LiveAuditEntry } from "@/lib/live-data";

export const Route = createFileRoute("/app/audit")({
  head: () => ({ meta: [{ title: "Audit Log · Matrix QA" }, { name: "robots", content: "noindex" }] }),
  component: AuditPage,
});

const catLabel: Record<LiveAuditCategory, string> = { console_warning: "Console Warning", network_noise: "Network Noise", visual_shift: "Visual Shift" };
const catTone: Record<LiveAuditCategory, string> = { console_warning: "text-warning bg-warning/10", network_noise: "text-info bg-info/10", visual_shift: "text-muted-foreground bg-surface-2" };

function AuditPage() {
  const live = useLivePortfolio();
  const [q, setQ] = useState("");
  const [cat, setCat] = useState<"all" | LiveAuditCategory>("all");
  const [selected, setSelected] = useState<LiveAuditEntry | null>(null);
  const list = live.auditEntries.filter((entry) => (cat === "all" || entry.category === cat) && (!q || `${entry.message} ${entry.runId}`.toLowerCase().includes(q.toLowerCase())));
  const counts = { total: live.auditEntries.length, warnings: live.auditEntries.filter((item) => item.category === "console_warning").length, network: live.auditEntries.filter((item) => item.category === "network_noise").length, visual: live.auditEntries.filter((item) => item.category === "visual_shift").length };
  return (
    <div className="mx-auto max-w-7xl px-4 py-6 md:px-8 md:py-8">
      <h1 className="font-display text-2xl font-semibold tracking-tight md:text-3xl">Audit Log</h1>
      <p className="mt-1 text-sm text-muted-foreground">Background telemetry returned by the backend noise gate, kept separate from primary hard findings.</p>
      {live.error && <div className="mt-5 rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{live.error}</div>}
      <div className="mt-5 grid grid-cols-2 gap-2 md:grid-cols-4"><MetricPill label="Total retained" value={counts.total} /><MetricPill label="Warnings" value={counts.warnings} /><MetricPill label="Network noise" value={counts.network} /><MetricPill label="Visual shifts" value={counts.visual} /></div>
      <div className="mt-4 flex flex-wrap items-center gap-2"><div className="flex flex-1 items-center gap-2 rounded-md border border-border bg-surface-2/40 px-3 py-1.5 md:max-w-md"><Search className="h-3.5 w-3.5 text-muted-foreground" /><input value={q} onChange={(event) => setQ(event.target.value)} placeholder="Search messages or run ID…" className="w-full bg-transparent font-mono text-xs outline-none placeholder:text-muted-foreground" /></div><div className="flex items-center gap-1 rounded-md border border-border bg-surface-2/40 p-1"><Filter className="ml-1 h-3 w-3 text-muted-foreground" />{(["all", "console_warning", "network_noise", "visual_shift"] as const).map((item) => <button key={item} onClick={() => setCat(item)} className={`rounded px-2 py-1 text-xs font-medium ${cat === item ? "bg-primary/15 text-foreground" : "text-muted-foreground"}`}>{item === "all" ? "All" : catLabel[item]}</button>)}</div></div>
      <section className="surface-card mt-4 overflow-hidden"><div className="hidden md:block"><div className="grid grid-cols-[110px_100px_130px_1fr_80px] items-center gap-3 border-b border-border bg-surface-2/40 px-4 py-2 font-mono text-[10px] uppercase tracking-wider text-muted-foreground"><span>Timestamp</span><span>Run</span><span>Category</span><span>Message</span><span /></div><ul>{list.map((entry) => <li key={entry.id}><button onClick={() => setSelected(entry)} className="grid w-full grid-cols-[110px_100px_130px_1fr_80px] items-center gap-3 border-b border-border px-4 py-2.5 text-left font-mono text-xs last:border-b-0 hover:bg-accent/30"><span className="text-muted-foreground">{entry.ts}</span><span className="text-primary">#{entry.runId.slice(-4)}</span><span><span className={`rounded px-1.5 py-0.5 text-[10px] uppercase ${catTone[entry.category]}`}>{catLabel[entry.category]}</span></span><span className="truncate text-foreground">{entry.message}</span><span className="text-right text-[10px] uppercase text-muted-foreground">Inspect</span></button></li>)}</ul></div><ul className="divide-y divide-border md:hidden">{list.map((entry) => <li key={entry.id}><button onClick={() => setSelected(entry)} className="block w-full px-4 py-3 text-left font-mono"><div className="flex items-center justify-between gap-2 text-[10px]"><span className={`rounded px-1.5 py-0.5 uppercase ${catTone[entry.category]}`}>{catLabel[entry.category]}</span><span className="text-muted-foreground">#{entry.runId.slice(-4)} · {entry.ts}</span></div><div className="mt-1 line-clamp-2 text-xs text-foreground">{entry.message}</div></button></li>)}</ul>{!live.loading && !list.length && <div className="p-8 text-center text-sm text-muted-foreground">No retained audit entries match those filters.</div>}{live.loading && <div className="p-8 text-center text-sm text-muted-foreground">Loading live audit entries…</div>}</section>
      {selected && <AuditDrawer entry={selected} onClose={() => setSelected(null)} />}
    </div>
  );
}
function AuditDrawer({ entry, onClose }: { entry: LiveAuditEntry; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex justify-end bg-background/70 backdrop-blur-sm"><div className="absolute inset-0" onClick={onClose} /><div className="relative flex w-full max-w-lg flex-col border-l border-border bg-surface"><div className="flex items-start justify-between border-b border-border px-5 py-4"><div><div className={`inline-flex rounded px-1.5 py-0.5 font-mono text-[10px] uppercase ${catTone[entry.category]}`}>{catLabel[entry.category]}</div><h2 className="mt-2 font-display text-base font-semibold">Retained backend audit event</h2></div><button onClick={onClose} aria-label="Close" className="rounded-md p-1.5 text-muted-foreground hover:bg-accent"><X className="h-4 w-4" /></button></div><div className="flex-1 space-y-4 overflow-y-auto p-5"><div><div className="mb-2 text-[11px] uppercase tracking-wider text-muted-foreground">Raw message</div><pre className="overflow-auto rounded-md border border-border bg-background/60 p-3 font-mono text-[11px] leading-relaxed">{entry.message}</pre></div><div><div className="mb-1 text-[11px] uppercase tracking-wider text-muted-foreground">Run</div><div className="font-mono text-xs">{entry.runId}</div></div>{entry.source && <div><div className="mb-1 text-[11px] uppercase tracking-wider text-muted-foreground">Source</div><div className="font-mono text-xs break-all">{entry.source}</div></div>}<div><div className="mb-1 text-[11px] uppercase tracking-wider text-muted-foreground">Retention reason</div><span className="inline-block rounded-md border border-border bg-surface-2/60 px-2 py-1 font-mono text-xs text-primary">{entry.reason}</span></div></div></div></div>; }
function MetricPill({ label, value }: { label: string; value: number }) { return <div className="surface-card px-4 py-3"><div className="text-[11px] uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-0.5 font-display text-2xl font-semibold">{value}</div></div>; }
