/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityTestingRouteImport } from './routes/accessibility-testing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticationTestingRouteImport } from './routes/authentication-testing'
import { Route as AutomatedBrowserTestingRouteImport } from './routes/automated-browser-testing'
import { Route as CiCdTestingRouteImport } from './routes/ci-cd-testing'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CrossBrowserTestingRouteImport } from './routes/cross-browser-testing'
import { Route as EndToEndTestingRouteImport } from './routes/end-to-end-testing'
import { Route as EvidenceBasedBugReportsRouteImport } from './routes/evidence-based-bug-reports'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as JavascriptErrorMonitoringRouteImport } from './routes/javascript-error-monitoring'
import { Route as MiaRouteImport } from './routes/mia'
import { Route as PlaywrightTestingRouteImport } from './routes/playwright-testing'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QaFixtureRouteImport } from './routes/qa-fixture'
import { Route as QaForSaasRouteImport } from './routes/qa-for-saas'
import { Route as QaForStartupsRouteImport } from './routes/qa-for-startups'
import { Route as SampleReportRouteImport } from './routes/sample-report'
import { Route as StagingEnvironmentTestingRouteImport } from './routes/staging-environment-testing'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VisualRegressionTestingRouteImport } from './routes/visual-regression-testing'
import { Route as WebApplicationTestingRouteImport } from './routes/web-application-testing'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppCreditsRouteImport } from './routes/app.credits'
import { Route as AppDiscoveryRouteImport } from './routes/app.discovery'
import { Route as AppEnvironmentsRouteImport } from './routes/app.environments'
import { Route as AppIssuesRouteImport } from './routes/app.issues'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppReliabilityRouteImport } from './routes/app.reliability'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRunsRouteImport } from './routes/app.runs'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppWorkforceRouteImport } from './routes/app.workforce'
import { Route as AuthConfirmEmailRouteImport } from './routes/auth.confirm-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as StaffInvitationsAcceptRouteImport } from './routes/staff-invitations.accept'
import { Route as StaffInvitationsDeclineRouteImport } from './routes/staff-invitations.decline'
import { Route as AppRunsIndexRouteImport } from './routes/app.runs.index'
import { Route as AppRunsRunIdRouteImport } from './routes/app.runs.$runId'
import { Route as AppSettingsBillingRouteImport } from './routes/app.settings.billing'
import { Route as AppSettingsOrganizationRouteImport } from './routes/app.settings.organization'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityTestingRoute = AccessibilityTestingRouteImport.update({
  id: '/accessibility-testing',
  path: '/accessibility-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationTestingRoute = AuthenticationTestingRouteImport.update({
  id: '/authentication-testing',
  path: '/authentication-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatedBrowserTestingRoute = AutomatedBrowserTestingRouteImport.update({
  id: '/automated-browser-testing',
  path: '/automated-browser-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const CiCdTestingRoute = CiCdTestingRouteImport.update({
  id: '/ci-cd-testing',
  path: '/ci-cd-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossBrowserTestingRoute = CrossBrowserTestingRouteImport.update({
  id: '/cross-browser-testing',
  path: '/cross-browser-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const EndToEndTestingRoute = EndToEndTestingRouteImport.update({
  id: '/end-to-end-testing',
  path: '/end-to-end-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceBasedBugReportsRoute = EvidenceBasedBugReportsRouteImport.update({
  id: '/evidence-based-bug-reports',
  path: '/evidence-based-bug-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const JavascriptErrorMonitoringRoute =
  JavascriptErrorMonitoringRouteImport.update({
    id: '/javascript-error-monitoring',
    path: '/javascript-error-monitoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const MiaRoute = MiaRouteImport.update({
  id: '/mia',
  path: '/mia',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaywrightTestingRoute = PlaywrightTestingRouteImport.update({
  id: '/playwright-testing',
  path: '/playwright-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QaFixtureRoute = QaFixtureRouteImport.update({
  id: '/qa-fixture',
  path: '/qa-fixture',
  getParentRoute: () => rootRouteImport,
} as any)
const QaForSaasRoute = QaForSaasRouteImport.update({
  id: '/qa-for-saas',
  path: '/qa-for-saas',
  getParentRoute: () => rootRouteImport,
} as any)
const QaForStartupsRoute = QaForStartupsRouteImport.update({
  id: '/qa-for-startups',
  path: '/qa-for-startups',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleReportRoute = SampleReportRouteImport.update({
  id: '/sample-report',
  path: '/sample-report',
  getParentRoute: () => rootRouteImport,
} as any)
const StagingEnvironmentTestingRoute =
  StagingEnvironmentTestingRouteImport.update({
    id: '/staging-environment-testing',
    path: '/staging-environment-testing',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualRegressionTestingRoute = VisualRegressionTestingRouteImport.update({
  id: '/visual-regression-testing',
  path: '/visual-regression-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const WebApplicationTestingRoute = WebApplicationTestingRouteImport.update({
  id: '/web-application-testing',
  path: '/web-application-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryRoute = AppDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentsRoute = AppEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesRoute = AppIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppReliabilityRoute = AppReliabilityRouteImport.update({
  id: '/reliability',
  path: '/reliability',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkforceRoute = AppWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AppRoute,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const StaffInvitationsAcceptRoute = StaffInvitationsAcceptRouteImport.update({
  id: '/staff-invitations/accept',
  path: '/staff-invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffInvitationsDeclineRoute = StaffInvitationsDeclineRouteImport.update({
  id: '/staff-invitations/decline',
  path: '/staff-invitations/decline',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRunsRoute,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AppRunsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-testing': typeof AccessibilityTestingRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/authentication-testing': typeof AuthenticationTestingRoute
  '/automated-browser-testing': typeof AutomatedBrowserTestingRoute
  '/ci-cd-testing': typeof CiCdTestingRoute
  '/cookies': typeof CookiesRoute
  '/cross-browser-testing': typeof CrossBrowserTestingRoute
  '/end-to-end-testing': typeof EndToEndTestingRoute
  '/evidence-based-bug-reports': typeof EvidenceBasedBugReportsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/javascript-error-monitoring': typeof JavascriptErrorMonitoringRoute
  '/mia': typeof MiaRoute
  '/playwright-testing': typeof PlaywrightTestingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/qa-fixture': typeof QaFixtureRoute
  '/qa-for-saas': typeof QaForSaasRoute
  '/qa-for-startups': typeof QaForStartupsRoute
  '/sample-report': typeof SampleReportRoute
  '/staging-environment-testing': typeof StagingEnvironmentTestingRoute
  '/terms': typeof TermsRoute
  '/visual-regression-testing': typeof VisualRegressionTestingRoute
  '/web-application-testing': typeof WebApplicationTestingRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credits': typeof AppCreditsRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/environments': typeof AppEnvironmentsRoute
  '/app/issues': typeof AppIssuesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/reliability': typeof AppReliabilityRoute
  '/app/reports': typeof AppReportsRoute
  '/app/runs': typeof AppRunsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/workforce': typeof AppWorkforceRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/staff-invitations/accept': typeof StaffInvitationsAcceptRoute
  '/staff-invitations/decline': typeof StaffInvitationsDeclineRoute
  '/app/': typeof AppIndexRoute
  '/app/runs/$runId': typeof AppRunsRunIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/organization': typeof AppSettingsOrganizationRoute
  '/app/runs/': typeof AppRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-testing': typeof AccessibilityTestingRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/authentication-testing': typeof AuthenticationTestingRoute
  '/automated-browser-testing': typeof AutomatedBrowserTestingRoute
  '/ci-cd-testing': typeof CiCdTestingRoute
  '/cookies': typeof CookiesRoute
  '/cross-browser-testing': typeof CrossBrowserTestingRoute
  '/end-to-end-testing': typeof EndToEndTestingRoute
  '/evidence-based-bug-reports': typeof EvidenceBasedBugReportsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/javascript-error-monitoring': typeof JavascriptErrorMonitoringRoute
  '/mia': typeof MiaRoute
  '/playwright-testing': typeof PlaywrightTestingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/qa-fixture': typeof QaFixtureRoute
  '/qa-for-saas': typeof QaForSaasRoute
  '/qa-for-startups': typeof QaForStartupsRoute
  '/sample-report': typeof SampleReportRoute
  '/staging-environment-testing': typeof StagingEnvironmentTestingRoute
  '/terms': typeof TermsRoute
  '/visual-regression-testing': typeof VisualRegressionTestingRoute
  '/web-application-testing': typeof WebApplicationTestingRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credits': typeof AppCreditsRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/environments': typeof AppEnvironmentsRoute
  '/app/issues': typeof AppIssuesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/reliability': typeof AppReliabilityRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/workforce': typeof AppWorkforceRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/staff-invitations/accept': typeof StaffInvitationsAcceptRoute
  '/staff-invitations/decline': typeof StaffInvitationsDeclineRoute
  '/app': typeof AppIndexRoute
  '/app/runs/$runId': typeof AppRunsRunIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/organization': typeof AppSettingsOrganizationRoute
  '/app/runs': typeof AppRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-testing': typeof AccessibilityTestingRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/authentication-testing': typeof AuthenticationTestingRoute
  '/automated-browser-testing': typeof AutomatedBrowserTestingRoute
  '/ci-cd-testing': typeof CiCdTestingRoute
  '/cookies': typeof CookiesRoute
  '/cross-browser-testing': typeof CrossBrowserTestingRoute
  '/end-to-end-testing': typeof EndToEndTestingRoute
  '/evidence-based-bug-reports': typeof EvidenceBasedBugReportsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/javascript-error-monitoring': typeof JavascriptErrorMonitoringRoute
  '/mia': typeof MiaRoute
  '/playwright-testing': typeof PlaywrightTestingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/qa-fixture': typeof QaFixtureRoute
  '/qa-for-saas': typeof QaForSaasRoute
  '/qa-for-startups': typeof QaForStartupsRoute
  '/sample-report': typeof SampleReportRoute
  '/staging-environment-testing': typeof StagingEnvironmentTestingRoute
  '/terms': typeof TermsRoute
  '/visual-regression-testing': typeof VisualRegressionTestingRoute
  '/web-application-testing': typeof WebApplicationTestingRoute
  '/app/audit': typeof AppAuditRoute
  '/app/credits': typeof AppCreditsRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/environments': typeof AppEnvironmentsRoute
  '/app/issues': typeof AppIssuesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/reliability': typeof AppReliabilityRoute
  '/app/reports': typeof AppReportsRoute
  '/app/runs': typeof AppRunsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/workforce': typeof AppWorkforceRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/staff-invitations/accept': typeof StaffInvitationsAcceptRoute
  '/staff-invitations/decline': typeof StaffInvitationsDeclineRoute
  '/app/': typeof AppIndexRoute
  '/app/runs/$runId': typeof AppRunsRunIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/organization': typeof AppSettingsOrganizationRoute
  '/app/runs/': typeof AppRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility-testing'
    | '/admin'
    | '/app'
    | '/auth'
    | '/authentication-testing'
    | '/automated-browser-testing'
    | '/ci-cd-testing'
    | '/cookies'
    | '/cross-browser-testing'
    | '/end-to-end-testing'
    | '/evidence-based-bug-reports'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/javascript-error-monitoring'
    | '/mia'
    | '/playwright-testing'
    | '/pricing'
    | '/privacy'
    | '/qa-fixture'
    | '/qa-for-saas'
    | '/qa-for-startups'
    | '/sample-report'
    | '/staging-environment-testing'
    | '/terms'
    | '/visual-regression-testing'
    | '/web-application-testing'
    | '/app/audit'
    | '/app/credits'
    | '/app/discovery'
    | '/app/environments'
    | '/app/issues'
    | '/app/notifications'
    | '/app/projects'
    | '/app/reliability'
    | '/app/reports'
    | '/app/runs'
    | '/app/settings'
    | '/app/workforce'
    | '/auth/confirm-email'
    | '/auth/reset-password'
    | '/staff-invitations/accept'
    | '/staff-invitations/decline'
    | '/app/'
    | '/app/runs/$runId'
    | '/app/settings/billing'
    | '/app/settings/organization'
    | '/app/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility-testing'
    | '/admin'
    | '/auth'
    | '/authentication-testing'
    | '/automated-browser-testing'
    | '/ci-cd-testing'
    | '/cookies'
    | '/cross-browser-testing'
    | '/end-to-end-testing'
    | '/evidence-based-bug-reports'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/javascript-error-monitoring'
    | '/mia'
    | '/playwright-testing'
    | '/pricing'
    | '/privacy'
    | '/qa-fixture'
    | '/qa-for-saas'
    | '/qa-for-startups'
    | '/sample-report'
    | '/staging-environment-testing'
    | '/terms'
    | '/visual-regression-testing'
    | '/web-application-testing'
    | '/app/audit'
    | '/app/credits'
    | '/app/discovery'
    | '/app/environments'
    | '/app/issues'
    | '/app/notifications'
    | '/app/projects'
    | '/app/reliability'
    | '/app/reports'
    | '/app/settings'
    | '/app/workforce'
    | '/auth/confirm-email'
    | '/auth/reset-password'
    | '/staff-invitations/accept'
    | '/staff-invitations/decline'
    | '/app'
    | '/app/runs/$runId'
    | '/app/settings/billing'
    | '/app/settings/organization'
    | '/app/runs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility-testing'
    | '/admin'
    | '/app'
    | '/auth'
    | '/authentication-testing'
    | '/automated-browser-testing'
    | '/ci-cd-testing'
    | '/cookies'
    | '/cross-browser-testing'
    | '/end-to-end-testing'
    | '/evidence-based-bug-reports'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/javascript-error-monitoring'
    | '/mia'
    | '/playwright-testing'
    | '/pricing'
    | '/privacy'
    | '/qa-fixture'
    | '/qa-for-saas'
    | '/qa-for-startups'
    | '/sample-report'
    | '/staging-environment-testing'
    | '/terms'
    | '/visual-regression-testing'
    | '/web-application-testing'
    | '/app/audit'
    | '/app/credits'
    | '/app/discovery'
    | '/app/environments'
    | '/app/issues'
    | '/app/notifications'
    | '/app/projects'
    | '/app/reliability'
    | '/app/reports'
    | '/app/runs'
    | '/app/settings'
    | '/app/workforce'
    | '/auth/confirm-email'
    | '/auth/reset-password'
    | '/staff-invitations/accept'
    | '/staff-invitations/decline'
    | '/app/'
    | '/app/runs/$runId'
    | '/app/settings/billing'
    | '/app/settings/organization'
    | '/app/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityTestingRoute: typeof AccessibilityTestingRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticationTestingRoute: typeof AuthenticationTestingRoute
  AutomatedBrowserTestingRoute: typeof AutomatedBrowserTestingRoute
  CiCdTestingRoute: typeof CiCdTestingRoute
  CookiesRoute: typeof CookiesRoute
  CrossBrowserTestingRoute: typeof CrossBrowserTestingRoute
  EndToEndTestingRoute: typeof EndToEndTestingRoute
  EvidenceBasedBugReportsRoute: typeof EvidenceBasedBugReportsRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JavascriptErrorMonitoringRoute: typeof JavascriptErrorMonitoringRoute
  MiaRoute: typeof MiaRoute
  PlaywrightTestingRoute: typeof PlaywrightTestingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  QaFixtureRoute: typeof QaFixtureRoute
  QaForSaasRoute: typeof QaForSaasRoute
  QaForStartupsRoute: typeof QaForStartupsRoute
  SampleReportRoute: typeof SampleReportRoute
  StagingEnvironmentTestingRoute: typeof StagingEnvironmentTestingRoute
  TermsRoute: typeof TermsRoute
  VisualRegressionTestingRoute: typeof VisualRegressionTestingRoute
  WebApplicationTestingRoute: typeof WebApplicationTestingRoute
  StaffInvitationsAcceptRoute: typeof StaffInvitationsAcceptRoute
  StaffInvitationsDeclineRoute: typeof StaffInvitationsDeclineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility-testing': {
      id: '/accessibility-testing'
      path: '/accessibility-testing'
      fullPath: '/accessibility-testing'
      preLoaderRoute: typeof AccessibilityTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication-testing': {
      id: '/authentication-testing'
      path: '/authentication-testing'
      fullPath: '/authentication-testing'
      preLoaderRoute: typeof AuthenticationTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automated-browser-testing': {
      id: '/automated-browser-testing'
      path: '/automated-browser-testing'
      fullPath: '/automated-browser-testing'
      preLoaderRoute: typeof AutomatedBrowserTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ci-cd-testing': {
      id: '/ci-cd-testing'
      path: '/ci-cd-testing'
      fullPath: '/ci-cd-testing'
      preLoaderRoute: typeof CiCdTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-browser-testing': {
      id: '/cross-browser-testing'
      path: '/cross-browser-testing'
      fullPath: '/cross-browser-testing'
      preLoaderRoute: typeof CrossBrowserTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/end-to-end-testing': {
      id: '/end-to-end-testing'
      path: '/end-to-end-testing'
      fullPath: '/end-to-end-testing'
      preLoaderRoute: typeof EndToEndTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-based-bug-reports': {
      id: '/evidence-based-bug-reports'
      path: '/evidence-based-bug-reports'
      fullPath: '/evidence-based-bug-reports'
      preLoaderRoute: typeof EvidenceBasedBugReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/javascript-error-monitoring': {
      id: '/javascript-error-monitoring'
      path: '/javascript-error-monitoring'
      fullPath: '/javascript-error-monitoring'
      preLoaderRoute: typeof JavascriptErrorMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mia': {
      id: '/mia'
      path: '/mia'
      fullPath: '/mia'
      preLoaderRoute: typeof MiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playwright-testing': {
      id: '/playwright-testing'
      path: '/playwright-testing'
      fullPath: '/playwright-testing'
      preLoaderRoute: typeof PlaywrightTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-fixture': {
      id: '/qa-fixture'
      path: '/qa-fixture'
      fullPath: '/qa-fixture'
      preLoaderRoute: typeof QaFixtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-for-saas': {
      id: '/qa-for-saas'
      path: '/qa-for-saas'
      fullPath: '/qa-for-saas'
      preLoaderRoute: typeof QaForSaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-for-startups': {
      id: '/qa-for-startups'
      path: '/qa-for-startups'
      fullPath: '/qa-for-startups'
      preLoaderRoute: typeof QaForStartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-report': {
      id: '/sample-report'
      path: '/sample-report'
      fullPath: '/sample-report'
      preLoaderRoute: typeof SampleReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staging-environment-testing': {
      id: '/staging-environment-testing'
      path: '/staging-environment-testing'
      fullPath: '/staging-environment-testing'
      preLoaderRoute: typeof StagingEnvironmentTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-regression-testing': {
      id: '/visual-regression-testing'
      path: '/visual-regression-testing'
      fullPath: '/visual-regression-testing'
      preLoaderRoute: typeof VisualRegressionTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-application-testing': {
      id: '/web-application-testing'
      path: '/web-application-testing'
      fullPath: '/web-application-testing'
      preLoaderRoute: typeof WebApplicationTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credits': {
      id: '/app/credits'
      path: '/credits'
      fullPath: '/app/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discovery': {
      id: '/app/discovery'
      path: '/discovery'
      fullPath: '/app/discovery'
      preLoaderRoute: typeof AppDiscoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/environments': {
      id: '/app/environments'
      path: '/environments'
      fullPath: '/app/environments'
      preLoaderRoute: typeof AppEnvironmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/issues': {
      id: '/app/issues'
      path: '/issues'
      fullPath: '/app/issues'
      preLoaderRoute: typeof AppIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reliability': {
      id: '/app/reliability'
      path: '/reliability'
      fullPath: '/app/reliability'
      preLoaderRoute: typeof AppReliabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs': {
      id: '/app/runs'
      path: '/runs'
      fullPath: '/app/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workforce': {
      id: '/app/workforce'
      path: '/workforce'
      fullPath: '/app/workforce'
      preLoaderRoute: typeof AppWorkforceRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/confirm-email': {
      id: '/auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/staff-invitations/accept': {
      id: '/staff-invitations/accept'
      path: '/staff-invitations/accept'
      fullPath: '/staff-invitations/accept'
      preLoaderRoute: typeof StaffInvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-invitations/decline': {
      id: '/staff-invitations/decline'
      path: '/staff-invitations/decline'
      fullPath: '/staff-invitations/decline'
      preLoaderRoute: typeof StaffInvitationsDeclineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/runs/': {
      id: '/app/runs/'
      path: '/'
      fullPath: '/app/runs/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof AppRunsRoute
    }
    '/app/runs/$runId': {
      id: '/app/runs/$runId'
      path: '/$runId'
      fullPath: '/app/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRunsRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/organization': {
      id: '/app/settings/organization'
      path: '/organization'
      fullPath: '/app/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppRunsRouteChildren {
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
}

const AppRunsRouteChildren: AppRunsRouteChildren = {
  AppRunsRunIdRoute: AppRunsRunIdRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
}

const AppRunsRouteWithChildren =
  AppRunsRoute._addFileChildren(AppRunsRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppCreditsRoute: typeof AppCreditsRoute
  AppDiscoveryRoute: typeof AppDiscoveryRoute
  AppEnvironmentsRoute: typeof AppEnvironmentsRoute
  AppIssuesRoute: typeof AppIssuesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReliabilityRoute: typeof AppReliabilityRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRunsRoute: typeof AppRunsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppWorkforceRoute: typeof AppWorkforceRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppCreditsRoute: AppCreditsRoute,
  AppDiscoveryRoute: AppDiscoveryRoute,
  AppEnvironmentsRoute: AppEnvironmentsRoute,
  AppIssuesRoute: AppIssuesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReliabilityRoute: AppReliabilityRoute,
  AppReportsRoute: AppReportsRoute,
  AppRunsRoute: AppRunsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppWorkforceRoute: AppWorkforceRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityTestingRoute: AccessibilityTestingRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthenticationTestingRoute: AuthenticationTestingRoute,
  AutomatedBrowserTestingRoute: AutomatedBrowserTestingRoute,
  CiCdTestingRoute: CiCdTestingRoute,
  CookiesRoute: CookiesRoute,
  CrossBrowserTestingRoute: CrossBrowserTestingRoute,
  EndToEndTestingRoute: EndToEndTestingRoute,
  EvidenceBasedBugReportsRoute: EvidenceBasedBugReportsRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  JavascriptErrorMonitoringRoute: JavascriptErrorMonitoringRoute,
  MiaRoute: MiaRoute,
  PlaywrightTestingRoute: PlaywrightTestingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  QaFixtureRoute: QaFixtureRoute,
  QaForSaasRoute: QaForSaasRoute,
  QaForStartupsRoute: QaForStartupsRoute,
  SampleReportRoute: SampleReportRoute,
  StagingEnvironmentTestingRoute: StagingEnvironmentTestingRoute,
  TermsRoute: TermsRoute,
  VisualRegressionTestingRoute: VisualRegressionTestingRoute,
  WebApplicationTestingRoute: WebApplicationTestingRoute,
  StaffInvitationsAcceptRoute: StaffInvitationsAcceptRoute,
  StaffInvitationsDeclineRoute: StaffInvitationsDeclineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
